                                          # Data Validation #

SELECT * FROM ADMISSIONS
LIMIT 10;
SELECT * FROM APPOINTMENTS
LIMIT 10;
SELECT * FROM DEPARTMENTS
LIMIT 10;
SELECT * FROM DOCTORS
LIMIT 10;
SELECT * FROM PATIENTS
LIMIT 10;

SELECT COUNT(*) FROM ADMISSIONS;
SELECT COUNT(*) FROM APPOINTMENTS;
SELECT COUNT(*) FROM DEPARTMENTS;
SELECT COUNT(*) FROM DOCTORS;
SELECT COUNT(*) FROM PATIENTS;


-- Checking For NULL Values
SELECT COUNT(*) FROM ADMISSIONS
WHERE ADMISSION_ID IS NULL;
SELECT COUNT(*) FROM APPOINTMENTS
WHERE APPOINTMENT_ID IS NULL;
SELECT COUNT(*) FROM DEPARTMENTS
WHERE DEPARTMENT_ID IS NULL;
SELECT COUNT(*) FROM DOCTORS
WHERE DOCTOR_ID IS NULL;
SELECT COUNT(*) FROM PATIENTS
WHERE PATIENT_ID IS NULL;


-- Check Missing Values In Important Columns
SELECT COUNT(*) FROM admissions
WHERE Revenue IS NULL
   OR Treatment_Cost IS NULL
   OR Satisfaction_Score IS NULL;
   
   
SELECT COUNT(*) FROM APPOINTMENTS
WHERE APPOINTMENT_ID IS NULL
OR PATIENT_ID IS NULL
OR DOCTOR_ID IS NULL
OR APPOINTMENT_STATUS IS NULL;

SELECT COUNT(*) FROM DEPARTMENTS
WHERE DEPARTMENT_NAME IS NULL;

SELECT COUNT(*) FROM DOCTORS
WHERE DOCTOR_NAME IS NULL
OR DEPARTMENT_ID IS NULL;

SELECT COUNT(*) FROM PATIENTS
WHERE AGE IS NULL
OR GENDER IS NULL; 


-- Check For Duplicates

SELECT ADMISSION_ID, COUNT(*)
FROM ADMISSIONS
GROUP BY ADMISSION_ID
HAVING COUNT(*) > 1;

SELECT APPOINTMENT_ID, COUNT(*)
FROM APPOINTMENTS
GROUP BY APPOINTMENT_ID
HAVING COUNT(*) > 1;

SELECT DEPARTMENT_ID, COUNT(*)
FROM DEPARTMENTS
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 1;

SELECT DOCTOR_ID, COUNT(*)
FROM DOCTORS
GROUP BY DOCTOR_ID
HAVING COUNT(*) > 1;

SELECT PATIENT_ID, COUNT(*)
FROM PATIENTS
GROUP BY PATIENT_ID
HAVING COUNT(*) > 1;


-- Validating Relationshsip

SELECT COUNT(*)
FROM ADMISSIONS A
LEFT JOIN PATIENTS P
ON A.PATIENT_ID = P.PATIENT_ID
WHERE P.PATIENT_ID IS NULL;


SELECT COUNT(*)
FROM APPOINTMENTS A
LEFT JOIN DOCTORS D
ON A.DOCTOR_ID = D.DOCTOR_ID
WHERE D.DOCTOR_ID IS NULL;

SELECT COUNT(*)
FROM DOCTORS D
LEFT JOIN DEPARTMENTS DP
ON D.DEPARTMENT_ID = DP.DEPARTMENT_ID
WHERE DP.DEPARTMENT_ID IS NULL;

SELECT COUNT(*)
FROM APPOINTMENTS P
LEFT JOIN PATIENTS PA
ON P.PATIENT_ID = PA.PATIENT_ID
WHERE PA.PATIENT_ID IS NULL;


SELECT COUNT(*)
FROM APPOINTMENTS A
LEFT JOIN DOCTORS D
ON D.DOCTOR_ID = D.DOCTOR_ID
WHERE D.DOCTOR_ID IS NULL;



SELECT * FROM ADMISSIONS;
SELECT MIN(REVENUE), MAX(REVENUE) FROM ADMISSIONS;
SELECT MIN(WAIT_TIME_MINUTES), MAX(WAIT_TIME_MINUTES) FROM ADMISSIONS;
SELECT MIN(SATISFACTION_SCORE), MAX(SATISFACTION_SCORE) FROM ADMISSIONS;
SELECT MIN(LENGTH_OF_STAY_DAYS), MAX(LENGTH_OF_STAY_DAYS) FROM ADMISSIONS;