-- Fix Dtypes

ALTER TABLE ADMISSIONS
MODIFY ADMISSION_ID VARCHAR(20),
MODIFY PATIENT_ID VARCHAR(20),
MODIFY DOCTOR_ID VARCHAR(20),
MODIFY ADMISSION_DATE DATE,
MODIFY DISCHARGE_DATE DATE;


ALTER TABLE APPOINTMENTS
MODIFY APPOINTMENT_ID VARCHAR(20),
MODIFY PATIENT_ID VARCHAR(20),
MODIFY DOCTOR_ID VARCHAR(20),
MODIFY APPOINTMENT_DATE DATE;


ALTER TABLE DEPARTMENTS
MODIFY DEPARTMENT_ID VARCHAR(20);


ALTER TABLE DOCTORS
MODIFY DOCTOR_ID VARCHAR(20),
MODIFY DEPARTMENT_ID VARCHAR(20);


ALTER TABLE PATIENTS
MODIFY PATIENT_ID VARCHAR(20),
MODIFY REGISTRATION_DATE DATE;


-- Creating Relationshsip (Constraints - Primary Key )

DESCRIBE ADMISSIONS;
ALTER TABLE ADMISSIONS
ADD PRIMARY KEY (ADMISSION_ID);

DESCRIBE APPOINTMENTS;
ALTER TABLE APPOINTMENTS
ADD PRIMARY KEY (APPOINTMENT_ID);

DESCRIBE DEPARTMENTS;
ALTER TABLE DEPARTMENTS
ADD PRIMARY KEY (DEPARTMENT_ID);

DESCRIBE DOCTORS;
ALTER TABLE DOCTORS
ADD PRIMARY KEY (DOCTOR_ID);

DESCRIBE PATIENTS;
ALTER TABLE PATIENTS
ADD PRIMARY KEY (PATIENT_ID);


-- Adding Foreign Keys

ALTER TABLE DOCTORS
ADD CONSTRAINT FK_DOCTORS_DEPARTMENT
FOREIGN KEY (DEPARTMENT_ID)
REFERENCES DEPARTMENTS(DEPARTMENT_ID);

ALTER TABLE ADMISSIONS
ADD CONSTRAINT FK_ADMISSIONS_PATIENT
FOREIGN KEY (PATIENT_ID)
REFERENCES PATIENTS(PATIENT_ID);

ALTER TABLE ADMISSIONS
ADD CONSTRAINT FK_ADMISSIONS_DOCTOR
FOREIGN KEY (DOCTOR_ID)
REFERENCES DOCTORS(DOCTOR_ID);

ALTER TABLE APPOINTMENTS
ADD CONSTRAINT FK_APPOINTMENTS_DOCTOR
FOREIGN KEY (DOCTOR_ID)
REFERENCES DOCTORS(DOCTOR_ID);

ALTER TABLE APPOINTMENTS
ADD CONSTRAINT FK_APPOINTMENTS_PATIENT
FOREIGN KEY (PATIENT_ID)
REFERENCES PATIENTS(PATIENT_ID);





