# Data Modeling #

CREATE DATABASE healthcare_analytics;
USE healthcare_analytics;

-- Creating Relationshsip (Constraints - Primary Key )

DESCRIBE ADMISSIONS;
ALTER TABLE ADMISSIONS
ADD PRIMARY KEY (ADMISSION_ID);

DESCRIBE APPOINTMENTS;
ALTER TABLE APPOINTMENTS
ADD PRIMARY KEY (APPOINTMENT_ID);

DESCRIBE DEPARTMENTS;
ALTER TABLE DEPARTMENTS
ADD PRIMARY KEY (DEPARTMENT_ID);

DESCRIBE DOCTORS;
ALTER TABLE DOCTORS
ADD PRIMARY KEY (DOCTOR_ID);

DESCRIBE PATIENTS;
ALTER TABLE PATIENTS
ADD PRIMARY KEY (PATIENT_ID);


-- Adding Foreign Keys

ALTER TABLE DOCTORS
ADD CONSTRAINT FK_DOCTORS_DEPARTMENT
FOREIGN KEY (DEPARTMENT_ID)
REFERENCES DEPARTMENTS(DEPARTMENT_ID);

ALTER TABLE ADMISSIONS
ADD CONSTRAINT FK_ADMISSIONS_PATIENT
FOREIGN KEY (PATIENT_ID)
REFERENCES PATIENTS(PATIENT_ID);

ALTER TABLE ADMISSIONS
ADD CONSTRAINT FK_ADMISSIONS_DOCTOR
FOREIGN KEY (DOCTOR_ID)
REFERENCES DOCTORS(DOCTOR_ID);

ALTER TABLE APPOINTMENTS
ADD CONSTRAINT FK_APPOINTMENTS_DOCTOR
FOREIGN KEY (DOCTOR_ID)
REFERENCES DOCTORS(DOCTOR_ID);

ALTER TABLE APPOINTMENTS
ADD CONSTRAINT FK_APPOINTMENTS_PATIENT
FOREIGN KEY (PATIENT_ID)
REFERENCES PATIENTS(PATIENT_ID);


-- MIN/MAX Checks
SELECT * FROM ADMISSIONS;
SELECT MIN(REVENUE), MAX(REVENUE) FROM ADMISSIONS;
SELECT MIN(WAIT_TIME_MINUTES), MAX(WAIT_TIME_MINUTES) FROM ADMISSIONS;
SELECT MIN(SATISFACTION_SCORE), MAX(SATISFACTION_SCORE) FROM ADMISSIONS;
SELECT MIN(LENGTH_OF_STAY_DAYS), MAX(LENGTH_OF_STAY_DAYS) FROM ADMISSIONS;