# Executive KPI`S

-- Total Patients >
SELECT DISTINCT COUNT(*) AS Total_Patients FROM PATIENTS;

-- Total Admissions >
SELECT DISTINCT COUNT(*) AS Total_Admissions FROM ADMISSIONS;

-- Total Revenue >
SELECT SUM(REVENUE) AS TOTAL_REVENUE FROM ADMISSIONS;

-- Average Wait Time
SELECT AVG(WAIT_TIME_MINUTES) AS AVG_WAIT_TIME FROM ADMISSIONS;

-- Average Length Of Stay
SELECT ROUND(AVG(LENGTH_OF_STAY_DAYS),2) AVG_LENGTH_OF_STAY FROM ADMISSIONS;

-- Average Satisfaction Score
SELECT ROUND(AVG(SATISFACTION_SCORE),2) AS AVG_SATISFACTION_SCORE FROM ADMISSIONS;