# Patients Analysis

SELECT * FROM PATIENTS;
SELECT * FROM ADMISSIONS;
-- Patients By Gender
SELECT GENDER, COUNT(PATIENT_ID) AS Total_Patients
FROM PATIENTS
GROUP BY GENDER
ORDER BY TOTAL_PATIENTS DESC;


-- Patients By Insurance Type
SELECT INSURANCE_TYPE, COUNT(PATIENT_ID) AS Total_Patients
FROM PATIENTS
GROUP BY INSURANCE_TYPE
ORDER BY TOTAL_PATIENTS;


-- Patients By City
SELECT CITY, COUNT(PATIENT_ID) AS Total_Patients
FROM PATIENTS
GROUP BY CITY
ORDER BY TOTAL_PATIENTS DESC;


-- Admissions By Gender
SELECT P.GENDER, COUNT(A.ADMISSION_ID) AS Total_Admissions
FROM PATIENTS P
LEFT JOIN ADMISSIONS A
ON P.PATIENT_ID = A.PATIENT_ID
GROUP BY P.GENDER
ORDER BY TOTAL_ADMISSIONS DESC;

-- Revenue By Gender
SELECT P.GENDER, SUM(A.REVENUE) AS Total_Revenue
FROM PATIENTS P
LEFT JOIN ADMISSIONS A
ON P.PATIENT_ID = A.PATIENT_ID
GROUP BY P.GENDER
ORDER BY TOTAL_REVENUE DESC;


-- 
-- Patients By Age Group
SELECT AGE  